// COURSES ACTIONS
export const FETCH_COURSE = "FETCH_COURSE";
export const SAVE_COURSE = "SAVE_COURSE";

// PROFILE ACTIONS
export const USER_INIT_COURSE = "USER_INIT_COURSE";
export const USER_SET_BEST_RESULT = "USER_SET_BEST_RESULT";

// SETTINGS ACTIONS
export const SET_SOUND = "SET_SOUND";
